### ISSUE TITLE
Use default as a fallback value

### ISSUE THREAD

**Issue by Pacheco95** [jquense/yup#1104]
I think many people use Yup to validate data and display some fancy feedback to the user. I'm just trying to verify if the data has met some criteria and if its not, just use a default value. But seem that it is not the Yup purpose. I have tried this but with an unexpected behaviour.

```javascript
const yup = require("yup");
const assert = require("assert");

const paginationSchema = yup.object().shape({
  page: yup.number().positive().integer().default(1),
  pageSize: yup.mixed().oneOf([5, 10, 25]).default(10),
  offset: yup.number().integer().positive().default(0)
});

const searchParams = new URLSearchParams("page=100&pageSize=-1&offset=bad");

const { page, pageSize, offset } = paginationSchema.cast({
  page: searchParams.get("page"),
  pageSize: searchParams.get("pageSize"),
  offset: searchParams.get("offset"),
});

assert(page === 1)
assert(pageSize === 10)
assert(offset === 0)
```

Type cast error:

```
node_modules/yup/lib/mixed.js:237
      throw new TypeError("The value of " + (options.path || 'field') + " could not be cast to a value " + ("that satisfies the schema type: \"" + resolvedSchema._type + "\". \n\n") + ("attempted value: " + formattedValue + " \n") + (formattedResult !== formattedValue ? "result of cast: " + formattedResult : ''));
      ^

TypeError: The value of offset could not be cast to a value that satisfies the schema type: "number". 

attempted value: bad 
result of cast: NaN
    at NumberSchema.cast (/redacted/node_modules/yup/lib/mixed.js:237:13)
    at /redacted/node_modules/yup/lib/object.js:178:63
    at Array.forEach (<anonymous>)
    at ObjectSchema._cast (/redacted/node_modules/yup/lib/object.js:161:11)
    at ObjectSchema.cast (/redacted/node_modules/yup/lib/mixed.js:232:33)
    at Object.<anonymous> (/redacted/tempCodeRunnerFile.javascript:12:53)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
```

Another example https://codesandbox.io/s/node-js-forked-7tete?file=/src/index.js

---

Can Yup solve this kind of issue? Or another validation library? I need some guide.

**Comment by jquense** [comment]
Defaults are used when the value is empty not when it's invalid. This use case isn't really supported out of the box, but you can get close to what you want with a transform. Or with a layer on top of your schema that catches cast errors and using the info on the errors, replaces the bad values with the defaults
