### ISSUE TITLE
Context always undefined when casting values for nested objects

### ISSUE THREAD

**Issue by fecruzb** [jquense/yup#1463]
Hi everyone, I'm getting an error inside `when` function saying that `foo.choice` is undefined but the context should be present. When validating without `strict` mode, yup tries to cast and ensure data types for all fields, but it is not preserving the same context during the process of casting.

My goal is to make only `bar.name` required when `foo.choice` is true otherwise `bar` should not be casted or validated.

Someone could help me with these? seems like a bug!

version: `0.31+`
https://codesandbox.io/s/cranky-brahmagupta-9lwyn?file=/src/index.js

```
const yup = require("yup");

const baseSchema = yup.object({

  // foo 
  foo: yup.object({
    choice: yup.bool().required(),
    name: yup.string().required(),
  }),

  // bar
  bar: yup
    .object({
      choice: yup.bool(),
      name: yup.string().when("$foo", (foo, schema) => {
        console.log(foo)
        return foo.choice ? schema.required() : schema
      } )
    })
});

const values = {
  foo: { choice: false, name: "test" },
};


baseSchema.validate(values, { recursive: true, strict: false, context: values, });
```

**Comment by fecruzb** [comment]
I changed back to version `0.30` and it seems to be working. Since I was in need to use `pick` and `omit` introduced in version `0.31` I end up doing the following solution with lodash:

```
import * as yup from "yup";
import _ from "lodash";

const pickSchema = (schema, paths) => {
  const shape = _.chain(paths)
    .keyBy()
    .mapValues((path) => yup.reach(schema, path))
    .value();
  return yup.object().shape(shape);
};

const schema = yup.object({
  foo: yup.object({
    choice: yup.bool().required(),
    name: yup.string().required()
  }),
  bar: yup.object({
    choice: yup.bool(),
    name: yup.string().when("$foo", (foo, s) => {
      return foo.choice ? s.required() : s;
    })
  }),
  other: yup.object({
    choice: yup.bool(),
    name: yup.string().required()
  })
});

const values = {
  foo: { choice: false, name: "tedst" }
};

const options = {
  context: values
};

const fooSchema = pickSchema(schema, ["foo", "bar"]);

fooSchema.validate(values, options);
```

**Comment by fecruzb** [comment]
@jquense Any update or feedback on this?

**Comment by fecruzb** [comment]
Thanks for the support.

**Comment by jquense** [comment]
Sorry I haven't been able to reproduce

**Comment by fecruzb** [comment]
Using latest version 1.0.2:

Here is a updated sandbox with comments:

https://codesandbox.io/p/sandbox/agitated-snowflake-xi3l73?file=%2Fpackage.json&selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A26%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A26%7D%5D


Here is the code inside the sandbox:

```const yup = require("yup");

const baseSchema = yup.object({
  // foo
  // foo.choice is required
  // foo.name is required
  foo: yup.object({
    choice: yup.bool().required(),
    name: yup.string().required(),
  }),

  // bar
  bar: yup.object({
    name: yup.string().when("$foo", (foo, schema) => {
      // if foo.choice is true, then bar.name is required
      // $foo is the context, that as inflated with the actual values
      // this part is being trigger 3 times in a single validate call
      // first one return [ undefined ] insted [{ choice: true, name: 'test' }]
      return foo.choice ? schema.required() : schema;
    }),
  }),
});

const values = {
  foo: { choice: true, name: "test" },
};

// No validation error is being throw, having foo.choice true
// and NOT HAVING bar.name that is conditionally required.
const validated = baseSchema.validateSync(values, {
  recursive: true,
  strict: false,
  context: values,
});

console.log("Valid", validated);
```

**Comment by fecruzb** [comment]
Here is the exactly same code, but using version `0.30.0`:

https://codesandbox.io/p/sandbox/purple-cdn-ytloho?file=%2Findex.js&selection=%5B%7B%22endColumn%22%3A19%2C%22endLineNumber%22%3A23%2C%22startColumn%22%3A19%2C%22startLineNumber%22%3A23%7D%5D

Here is the run log:

```
yarn run v1.22.19

{ choice: true, name: 'test' }

/project/sandbox/node_modules/yup/lib/mixed.js:357
      if (err) throw err;
               ^
ValidationError: bar.name is a required field
    at createError (/project/sandbox/node_modules/yup/lib/util/createValidation.js:49:19)
    at validate (/project/sandbox/node_modules/yup/lib/util/createValidation.js:91:83)
    at runTests (/project/sandbox/node_modules/yup/lib/util/runTests.js:28:5)
    at /project/sandbox/node_modules/yup/lib/mixed.js:319:29
    at /project/sandbox/node_modules/yup/lib/util/async.js:20:8
    at finishTestRun (/project/sandbox/node_modules/yup/lib/util/runTests.js:56:9)
    at validate (/project/sandbox/node_modules/yup/lib/util/createValidation.js:91:103)
    at runTests (/project/sandbox/node_modules/yup/lib/util/runTests.js:28:5)
    at StringSchema._validate (/project/sandbox/node_modules/yup/lib/mixed.js:310:34)
    at StringSchema.validate (/project/sandbox/node_modules/yup/lib/mixed.js:338:51) {
  value: { bar: { name: undefined }, foo: { choice: true, name: 'test' } },
  path: 'bar.name',
  type: 'required',
  errors: [ 'bar.name is a required field' ],
  inner: [],
  params: {
    value: undefined,
    originalValue: undefined,
    label: undefined,
    path: 'bar.name'
  }
}
error Command failed with exit code 1.
```

**Comment by fecruzb** [comment]
My project heavily relies on `.when` conditions and I as not able to upgrade yup from 0.30.0 since then. 
Maybe I'm doing something wrong? Can some one help me to achieve same results or to confirm that is really a bug?

I checked change logs for 0.31.0 and the breaking changes but no mention of a behavior change on `.when` + context usage.

Also its being called 3 times on a single validation. That's can be correct.

**Comment by fecruzb** [comment]
My guess was to make `bar` object required as well, but not lucky on version `1.0.2`:

```jsx
const yup = require("yup");

const baseSchema = yup.object().shape({
  // foo
  // foo.choice is required
  // foo.name is required
  foo: yup.object().shape({
    choice: yup.bool().required(),
    name: yup.string().required(),
  }),

  // bar
  bar: yup
    .object()
    .shape({
      name: yup.string().when("$foo", (foo, schema) => {
        // if foo.choice is true, then bar.name is required
        // $foo is the context, that as inflated with the actual values
        // this part is being triggered 3 times in a single validate call
        // first one return [ undefined ] insted [{ choice: true, name: 'test' }]
        console.log(foo);
        return foo.choice ? schema.required() : schema;
      }),
    })
    .when("$foo", (foo, schema) => {
      console.log(foo);
      return foo.choice ? schema.required() : schema;
    }),
});

const values = {
  foo: { choice: true, name: "test" },
};

// No validation error is being throw, having foo.choice true
// and NOT HAVING bar.name that is conditionally required.
const validated = baseSchema.validateSync(values, {
  recursive: true,
  strict: false,
  context: values,
});

console.log("Valid", validated);
```

But got same output:

```
yarn run v1.22.19
$ node index.js
[ { choice: true, name: 'test' } ]
[ undefined ]
[ { choice: true, name: 'test' } ]
[ { choice: true, name: 'test' } ]
[ { choice: true, name: 'test' } ]
Valid { bar: {}, foo: { choice: true, name: 'test' } }
Done in 0.10s.
``

**Comment by fecruzb** [comment]
Using `foo` outside the context as a sibling also didn't worked:

```jsx
const baseSchema = yup.object().shape({
  // foo
  // foo.choice is required
  // foo.name is required
  foo: yup.object().shape({
    choice: yup.bool().required(),
    name: yup.string().required(),
  }),

  // bar
  bar: yup
    .object()
    .shape({
      name: yup.string().when("$foo", (foo, schema) => {
        // if foo.choice is true, then bar.name is required
        // $foo is the context, that as inflated with the actual values
        // this part is being triggered 3 times in a single validate call
        // first one return [ undefined ] insted [{ choice: true, name: 'test' }]
        console.log(foo);
        return foo.choice ? schema.required() : schema;
      }),
    })
    .when("foo", (foo, schema) => {
      return foo.choice ? schema.required() : schema;
    }),
});
```

**Comment by fecruzb** [comment]
Last try, enable `strict: true` and got same results for all cases:

```js
const yup = require("yup");

const baseSchema = yup.object().shape({
  // foo
  // foo.choice is required
  // foo.name is required
  foo: yup.object().shape({
    choice: yup.bool().required(),
    name: yup.string().required(),
  }),

  // bar
  bar: yup
    .object()
    .shape({
      name: yup.string().when("$foo", (foo, schema) => {
        // if foo.choice is true, then bar.name is required
        // $foo is the context, that as inflated with the actual values
        // this part is being triggered 3 times in a single validate call
        // first one return [ undefined ] insted [{ choice: true, name: 'test' }]
        console.log(foo);
        return foo.choice ? schema.required() : schema;
      }),
    })
    .when("foo", (foo, schema) => {
      return foo.choice ? schema.required() : schema;
    }),
});

const values = {
  foo: { choice: true, name: "test" },
};

// No validation error is being throw, having foo.choice true
// and NOT HAVING bar.name that is conditionally required.
const validated = baseSchema.validateSync(values, {
  recursive: true,
  strict: true,
  context: values,
});

console.log("Valid", validated);
```

at least didn't ran 3 times but no error throw yet

```
yarn run v1.22.19
$ node index.js
Valid { foo: { choice: true, name: 'test' } }
Done in 0.10s.
```

**Comment by jquense** [comment]
ah i see the issue. The first call is an internal call to `getDefault` to fill out the missing bits of the value, it's not passing the options through. Will fix

**Comment by fecruzb** [comment]
Appreciate it man. Thanks by having a look into it.

**Comment by nasir-aviva** [comment]
Hi @jquense any update? Cheers

**Comment by jgprimaki** [comment]
Hi, @jquense. Any updates?

**Comment by sousaweb** [comment]
It seems using $ in the beginning of your key will make it work. I was using .when('register_information.type') inside a nested object, and it was undefined, but after changing to .when('$register_information.type') now it is working fine.
