### ISSUE TITLE
ts-node complains about yup/lib not exporting InferType

### ISSUE THREAD

**Issue by eensander** [jquense/yup#1605]
**Describe the bug**
When attempting to run my typescript script using **ts-node**, the compiler complains about the module `"../node_modules/yup/lib"` not having an exported member `'InferType'`. Strange is that all of the other types **are** being imported, just not InferType. 

It seems that, when compiling the script with `tsc file.ts` and executing the script with `node file.js` the code does work.

The error I get in my project: 
```
$ npx ts-node src/playground/example.ts 

/home/sander/project/node_modules/ts-node/src/index.ts:307
        throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset))
              ^
TSError: ⨯ Unable to compile TypeScript
src/playground/example.ts (6,41): Module '"../../node_modules/yup/lib"' has no exported member 'InferType'. (2305)
    at getOutput (/home/sander/project/node_modules/ts-node/src/index.ts:307:15)
    at /home/sander/project/node_modules/ts-node/src/index.ts:336:16
    at Object.compile (/home/sander/project/node_modules/ts-node/src/index.ts:498:11)
    at Module.m._compile (/home/sander/project/node_modules/ts-node/src/index.ts:392:43)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .ts] (/home/sander/project/node_modules/ts-node/src/index.ts:395:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at Object.<anonymous> (/home/sander/project/node_modules/ts-node/src/_bin.ts:182:12)
```

**To Reproduce**
I don't really use codesandbox.io often, so I'm not sure if I implemented the reproduction correctly. However I was quite easily able to reproduce the problem I'm encountering.

1. Go to this [sandbox](https://codesandbox.io/s/sparkling-pine-64qfsj?file=/package.json)
2. Open a new terminal and execute `$ npx ts-node problem.ts`

The error produced in my sandbox seems very similar:
```
$ npx ts-node problem.ts

/sandbox/node_modules/ts-node/src/index.ts:307
        throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset))
              ^
TSError: ⨯ Unable to compile TypeScript
problem.ts (1,41): Module '"./node_modules/yup/lib"' has no exported member 'InferType'. (2305)
    at getOutput (/sandbox/node_modules/ts-node/src/index.ts:307:15)
    at /sandbox/node_modules/ts-node/src/index.ts:336:16
    at Object.compile (/sandbox/node_modules/ts-node/src/index.ts:498:11)
    at Module.m._compile (/sandbox/node_modules/ts-node/src/index.ts:392:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.require.extensions.<computed> [as .ts] (/sandbox/node_modules/ts-node/src/index.ts:395:12)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at Object.<anonymous> (/sandbox/node_modules/ts-node/src/_bin.ts:182:12)
```

**Expected behavior**
I expect the InferType module to be correctly imported.

**Platform (please complete the following information):**
The problem seems to occur in the sandbox, and on my system with:
 - yup version `^0.32.11`
 - `$ ts-node --version`
   - `v8.6.2`

 - `$ npx ts-node --version`
```
ts-node v3.3.0
node v16.13.2
typescript v3.3.3333
```

**Additional context**
When looking in the file `node_modules/yup/lib/index.js` I am unable to find 'InferType', while it is found in `node_modules/yup/lib/index.d.ts`. I'm not sure whether this is useful.

Also I'm not sure if this is a problem with the `ts-node` interpreter itself or yup, or my installation. Any help is appreciated!

**Comment by jquense** [comment]
you generally shouldn't be running yup through the typescript compiler. it's already compiled and its type def is shipped with it. I'm not sure what your doing in your setup but I don't think its's a yup issue.

**Comment by eensander** [comment]
Thanks for the quick response. I switched to tsc-watch which suffices currently.
