### ISSUE TITLE
Getting error while trying to concatenate two schemas

### ISSUE THREAD

**Issue by justinthomas0789** [jquense/yup#1957]
- When I try to concatenate two schemas, I'm getting an error

> Uncaught TypeError: newItems.forEach is not a function
>     at ReferenceSet.merge (index.esm.js:416:1)
>     at ObjectSchema.concat (index.esm.js:555:1)
>     at ObjectSchema.concat (index.esm.js:1749:1)
>     at Profile (profile.js:162:1)
>     at renderWithHooks (react-dom.development.js:16305:1)
>     at updateFunctionComponent (react-dom.development.js:19588:1)
>     at mountLazyComponent (react-dom.development.js:19959:1)
>     at beginWork (react-dom.development.js:21593:1)
>     at beginWork$1 (react-dom.development.js:27426:1)
>     at performUnitOfWork (react-dom.development.js:26557:1)

Here is my code
```
const passwordRegex =
  /^(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#$%^&*()_+\-=[\]{};':"\\|,.<>/?]|.{12,}|.{1,}).{3,}$/

const ValidationPassword = yup.object().shape({
  password: yup.string().required().min(8).max(128).matches(passwordRegex),
  confirmPassword: yup
    .string()
    .required()
    .oneOf([yup.ref('password'), null])
})
```

```
const schema = yup.object().shape({
    username: yup.string().required(),
    email: yup.string().email().required(),
    name: yup.string(),
    surname: yup.string(),
    personalNumber: yup.string().max(15).nullable(),
    retries: yup.number(),
    zoneId: yup.string().nullable(),
    countryId: yup.string().nullable(),
    isActive: yup.boolean(),
    promptExtranetTreatmentsAdvice: yup.boolean(),
    absent: yup.boolean(),
    createdBySuperUser: yup.boolean(),
    disabledBySuperUser : yup.boolean(),
    clinicId: yup.string().nullable(),
    companyId: yup.string().nullable(),
  }).concat(ValidationPassword)
```

**Comment by antoinerousseau** [comment]
same here, how did you solve this?

**Comment by PatrykJamroz** [comment]
same for me, any solutions found?
