### ISSUE TITLE
Using `when` Schema throws TypeError: branch is not a function

### ISSUE THREAD

**Issue by zlayine** [jquense/yup#1962]
**Describe the bug**
Using `when` Schema shows error on the `is` condition that there is no overload matches this call in VSCode and on the browser it shows :
```
Uncaught (in promise) TypeError: branch is not a function
    at Condition.fn (index.esm.js:175:51)
    at Condition.resolve (index.esm.js:188:23)
    at index.esm.js:586:71
    at Array.reduce (<anonymous>)
    at NumberSchema.resolve (index.esm.js:586:27)
    at ObjectSchema._cast (index.esm.js:1670:23)
    at ObjectSchema._validate (index.esm.js:636:20)
    at ObjectSchema._validate (index.esm.js:1710:11)
    at index.esm.js:745:52
    at new Promise (<anonymous>)
```

Example i used: 

```JavaScript
const validation = yup.object({
    address: yup.string().required(),
    percentage: yup.number().when('address', {
        is: (val: string) => val !== '' && val !== null,
        then: yup.number().min(0).max(100).required(),
        otherwise: yup.number().nullable().transform(emptyToNullTransform),
    }),
});
```

**Comment by baermathias** [comment]
I am having the same error. I first used version 1, but there I got another error:
```
Object literal may only specify known properties, and 'is' does not exist in type 'ConditionBuilder<NumberSchema<number | undefined, AnyObject, undefined, "">>'.
```
So I switched to `0.32.11`, which made the error disappear, but I still have the error `Uncaught (in promise) TypeError: branch is not a function` with the old version.

I am using exactly the same syntax as described in this issue

**Comment by jquense** [comment]
The syntax is is wrong in v1. Please read the docs for what it should be, thanks

**Comment by zlayine** [comment]
i had to use arrow function for `then` and `otherwise`
