### ISSUE TITLE
string is not nullable when a condition is set

### ISSUE THREAD

**Issue by fourq** [jquense/yup#2]
If I set a max, nullable isn't taken into consideration.

```javascript
Yup.string().max(150, 'Invalid Address Cont.').nullable()
```

Schema: https://gist.github.com/13961916b067a9cfd291 
Test: https://gist.github.com/2f440aa2df4bdb5d5be3

**Comment by jquense** [comment]
good catch!, I'll see what I can do

**Comment by fourq** [comment]
The same test is throwing:

```
/Users/rocky/src/code/react/pastoral-acts-validation/node_modules/yup/lib/util/_.js:36
    var targetVal = target[key];
                          ^
TypeError: Cannot read property '_deps' of undefined
    at merge (/Users/rocky/src/code/react/pastoral-acts-validation/node_modules/yup/lib/util/_.js:36:27)
    at merge (/Users/rocky/src/code/react/pastoral-acts-validation/node_modules/yup/lib/util/_.js:39:67)
    at Object.merge (/Users/rocky/src/code/react/pastoral-acts-validation/node_modules/yup/lib/util/_.js:39:67)
    at ObjectSchema.SchemaType.concat (/Users/rocky/src/code/react/pastoral-acts-validation/node_modules/yup/lib/mixed.js:45:14)
    at Object.<anonymous> (/Users/rocky/src/code/react/pastoral-acts-validation/modules/act.js:69:125)
    at Module._compile (module.js:460:26)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/rocky/src/code/react/pastoral-acts-validation/node_modules/lab/lib/coverage.js:29:36)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/rocky/src/code/react/pastoral-acts-validation/modules/index.js:3:112)
    at Module._compile (module.js:460:26)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/rocky/src/code/react/pastoral-acts-validation/node_modules/lab/lib/coverage.js:29:36)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/rocky/src/code/react/pastoral-acts-validation/test/act.js:6:16)
    at Module._compile (module.js:460:26)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/rocky/src/code/react/pastoral-acts-validation/node_modules/lab/lib/coverage.js:34:28)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /Users/rocky/src/code/react/pastoral-acts-validation/node_modules/lab/lib/cli.js:105:23
    at Array.forEach (native)
    at Object.internals.traverse (/Users/rocky/src/code/react/pastoral-acts-validation/node_modules/lab/lib/cli.js:101:19)
    at Object.exports.run (/Users/rocky/src/code/react/pastoral-acts-validation/node_modules/lab/lib/cli.js:50:29)
    at Object.<anonymous> (/Users/rocky/src/code/react/pastoral-acts-validation/node_modules/lab/bin/lab:3:23)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by jquense** [comment]
that's what I get for not having a test on the the `merge()` function
