### ISSUE TITLE
Inferred type of object with noUnknown set to false doesn't allow additional non-specified keys in TypeScript

### ISSUE THREAD

**Issue by GlenTiki** [jquense/yup#2054]
**Describe the bug**

When you set `.noUnknown(false)` on an object schema, the typescript inferred type should allow non-specified keys in the shape.

**To Reproduce**

Create a typescript file like below and validate the types in it it using the typescript compiler

All typescript scripts can be put in a `index.ts` file

```ts
import * as yup from "yup"

const myExample = yup.object({
    a: yup.string().required()
}).noUnknown(false)

type MyExample = yup.InferType<typeof myExample>

const broken: MyExample = {
    a: "a string",
    b: "not allowed"
}
```
run with `npx tsc --noEmit ./index.ts `

```
./index.ts:11:5 - error TS2322: Type '{ a: string; b: string; }' is not assignable to type '{ a?: string; }'.
  Object literal may only specify known properties, and 'b' does not exist in type '{ a?: string; }'.

11     b: "allowed"
       ~~~~~~~~~~~~
```

**Expected behavior**

This shouldn't cause a type error, and typing should work as expected.

**Platform (please complete the following information):**
 - Node 16, Typescipt 4.4.4
 - yup@1.2.0

**Additional context**

The following is valid and usable as a workaround:

```ts
import * as yup from "yup"

const myExample = yup.object<{[k: string]: any}>({
    a: yup.string().required()
}).noUnknown(false)

type MyExample = yup.InferType<typeof myExample>

const broken: MyExample = {
    a: "a string",
    b: "allowed"
}
```

However, this breaks some of the nicer, more complex compiler tooling, so, it breaks ts checks for the next example - it compiles when it shouldn't.

```ts
import * as yup from "yup"

const myExample = yup.object<{[k: string]: any}>({
    a: yup.string().oneOf(["valid"]).required()
}).noUnknown(false)

type MyExample = yup.InferType<typeof myExample>

const working: MyExample = {
    a: "valid",
    b: "allowed"
}

const shouldntWorkButDoes: MyExample = {
    a: "invalid",
    b: "allowed"
}

myExample.validateSync(working)
myExample.validateSync(shouldntWorkButDoes)
```

however, at runtime, it errors:

```
/Users/glen/work/scratchpad/node_modules/yup/index.js:769
      throw error;
      ^

ValidationError: a must be one of the following values: valid
    at Object.createError (/Users/glen/work/scratchpad/node_modules/yup/index.js:305:21)
    at Object.test (/Users/glen/work/scratchpad/node_modules/yup/index.js:967:55)
    at validate (/Users/glen/work/scratchpad/node_modules/yup/index.js:339:35)
    at StringSchema.runTests (/Users/glen/work/scratchpad/node_modules/yup/index.js:708:7)
    at StringSchema._validate (/Users/glen/work/scratchpad/node_modules/yup/index.js:652:10)
    at /Users/glen/work/scratchpad/node_modules/yup/index.js:747:58
    at ObjectSchema.runTests (/Users/glen/work/scratchpad/node_modules/yup/index.js:708:7)
    at /Users/glen/work/scratchpad/node_modules/yup/index.js:1744:12
    at nextOnce (/Users/glen/work/scratchpad/node_modules/yup/index.js:694:7)
    at finishTestRun (/Users/glen/work/scratchpad/node_modules/yup/index.js:713:11) {
  value: { a: 'invalid', b: 'allowed' },
  path: 'a',
  type: 'oneOf',
  errors: [ 'a must be one of the following values: valid' ],
  params: {
    value: 'invalid',
    originalValue: 'invalid',
    label: undefined,
    path: 'a',
    spec: {
      strip: false,
      strict: false,
      abortEarly: true,
      recursive: true,
      nullable: false,
      optional: false,
      coerce: true
    },
    values: 'valid',
    resolved: [ 'valid' ]
  },
  inner: []
}
```

**Comment by GlenTiki** [comment]
I have a workaround that's breaking the compiler as expected:

```ts
import * as yup from "yup"

const myExampleSchema = yup.mixed((input): input is yup.AnyObject => input).concat(yup.object({
    a: yup.string().oneOf(["valid"]).required()
}).noUnknown(false))

const parentSchema = yup.object({
    example: myExampleSchema.required()
})


type Parent = yup.InferType<typeof parentSchema>

const working: Parent = {
    example: {
        a: "valid",
        b: "allowed"
    }
}

const shouldntWork: Parent = {
    example: {
        a: "invalid",
        b: "allowed"
    }
}

parentSchema.validateSync(working)
parentSchema.validateSync(shouldntWork)
```

Breaking as expected:
```
./index.ts:23:9 - error TS2322: Type '"invalid"' is not assignable to type '"valid"'.

23         a: "invalid",
           ~


Found 1 error.
```
