### ISSUE TITLE
error checking  Array elements of default

### ISSUE THREAD

**Issue by mhaslbec** [jquense/yup#2150]
**Describe the bug**
When the validate function receives `undefined` and a default is specified, the elements of the array can not be checked.
`.of(yup.number().required())` tries to validate original value `undefined` instead of the Array supplied by `.default
`
**To Reproduce**

```
const ARRAY_OF_NUMBERS = yup
  .array()
  .of(yup.number().required())
  .default([1])
  .validateSync(undefined);
```

**Expected behavior**
`ARRAY_OF_NUMBERS` should use the specified

**Actual behavior**
this Error
```
/node_modules/yup/index.js:748
      originalValue: originalParent[k],
                                   ^

TypeError: Cannot read properties of undefined (reading '0')
    at NumberSchema.asNestedTest (/home/michael/git/digitalplanner/backend/node_modules/yup/index.js:748:36)
    at /home/michael/git/digitalplanner/backend/node_modules/yup/index.js:2002:34
    at nextOnce (/home/michael/git/digitalplanner/backend/node_modules/yup/index.js:703:7)
    at ArraySchema.runTests (/home/michael/git/digitalplanner/backend/node_modules/yup/index.js:707:24)
    at /home/michael/git/digitalplanner/backend/node_modules/yup/index.js:672:12
    at nextOnce (/home/michael/git/digitalplanner/backend/node_modules/yup/index.js:703:7)
    at finishTestRun (/home/michael/git/digitalplanner/backend/node_modules/yup/index.js:722:11)
    at handleResult (/home/michael/git/digitalplanner/backend/node_modules/yup/index.js:329:124)
    at validate (/home/michael/git/digitalplanner/backend/node_modules/yup/index.js:352:5)
    at ArraySchema.runTests (/home/michael/git/digitalplanner/backend/node_modules/yup/index.js:717:7)
```

**Platform (please complete the following information):**
Tested on different Node versions:
 - Node 20.10.0
 - Node 16.18.1
 - Node 18.16.0

 - yup after 0.32.11
 
**Additional context**
This was working as expected in v0.32.11, but breaks afterwards

**Comment by Drakeguard** [comment]
same issue for me (L541) throws the error because the orginal value is null and it tries to access it
https://github.com/jquense/yup/blob/d00abc331801388cb572a07094ba0cb803a50d5d/src/schema.ts#L533-L551

**Comment by mhaslbec** [comment]
> is there a workaround for it?

Hi, I have not found a workaround using yup, however my company has switched to zod in new Projects, mostly because of the better typescript support. 
With zod, you should get an error if you accidently try to pass anything other than an array of numbers in my example. 
If you want, you can give zod a try, otherwise its best to apply the default manually before passing to validateSync

**Comment by Drakeguard** [comment]
Hi,
thanks for the response!
My problem is that I have to update an app that was recently still at version 0.33.x, and everything is very intertwined :/

I guess I’ll have no choice but to set the default values myself!
Thanks for the tip :)
