### ISSUE TITLE
Issue with running tests

### ISSUE THREAD

**Issue by moltar** [jquense/yup#235]
Was going to see if I can fix #234, but could not get the test suite to run.

But always getting the following:

## Error

```
$> npm run testonly
 FAIL  test/date.js
  ● Test suite failed to run

    [BABEL] ./yup/test-setup.js: Invalid Option: target is not a valid top-level option.
            Maybe you meant to use 'targets'? (While processing: "./yup/node_modules/babel-preset-jason/index.js$0")

      at validateTopLevelOptions (node_modules/@babel/preset-env/lib/normalize-options.js:47:13)
      at normalizeOptions (node_modules/@babel/preset-env/lib/normalize-options.js:149:3)
      at _default (node_modules/@babel/preset-env/lib/index.js:164:37)
      at node_modules/@babel/helper-plugin-utils/lib/index.js:19:12
      at loadDescriptor (node_modules/@babel/core/lib/config/full.js:157:14)
      at cachedFunction (node_modules/@babel/core/lib/config/caching.js:32:19)
      at loadPresetDescriptor (node_modules/@babel/core/lib/config/full.js:227:63)
      at config.presets.map.descriptor (node_modules/@babel/core/lib/config/full.js:72:19)
          at Array.map (<anonymous>)
      at recurseDescriptors (node_modules/@babel/core/lib/config/full.js:70:38)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.436s
Ran all test suites matching /test\/date.js/i.
```

## Tried:

```
npm run testonly
npm run test-all
```

**Comment by jquense** [comment]
yes i need to upgrade the babel preset, nuking and reinstalling should fix it
