### ISSUE TITLE
.when(field, ...) must have field defined in schema or error is thrown

### ISSUE THREAD

**Issue by derek-duncan** [jquense/yup#365]
Example schema:
```javascript
const Schema = Yup.object({
  type: Yup.string(),
  value: Yup.string().when("type", (type, schema) => {
    return type === "numeric" ? schema.required("Required") : schema;
  })
});
```

I kept getting the error `promise.then is not a function` when writing my `.when()` validations. I did some digging, and it looks like the field you're referencing in the `.when(field, ...)` must be defined in the schema, or the validation breaks.

This also only happens when `abortEarly` is `false`.

The error comes from this line: https://github.com/jquense/yup/blob/41d23d6ea1df080d783f67dda54e5b8a609dac0d/src/util/runValidations.js#L38-L46

If you trace that back, you see that the `settled` function is getting passed an array of promises from `runValidations`'s `options.validations`.

https://github.com/jquense/yup/blob/41d23d6ea1df080d783f67dda54e5b8a609dac0d/src/util/runValidations.js#L79-L83

You can see in `src/object.js` that `runValidations` is called. It's called with a `validations` parameter that is generated from the fields. Each field in `validations` gets a promise returned when it's validated. However, if the field cannot be found in the (this is what happens when using `when`), it returns `true` by default. Since `true` is not a promise, it eventually throws an error in `settled`.

I'm not sure what the fix is, but I know the problem and have a reproduction.

[![Edit yup-bug-reproduction](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nnpl5w15wm?expanddevtools=1&module=%2Fsrc%2Findex.test.js&previewwindow=tests)

**Full Error:**
```
promise.then is not a function

TypeError: promise.then is not a function
    at settle (https://yyyqp7y8x.codesandbox.io/src/util/runValidations.js:65:20)
    at Array.map (<anonymous>)
    at settled (https://yyyqp7y8x.codesandbox.io/src/util/runValidations.js:72:37)
    at collectErrors (https://yyyqp7y8x.codesandbox.io/src/util/runValidations.js:84:10)
    at runValidations (https://yyyqp7y8x.codesandbox.io/src/util/runValidations.js:115:10)
    at eval (https://yyyqp7y8x.codesandbox.io/src/object.js:224:43)
```

**Comment by chrismcleod** [comment]
moved passed this by adding to runValidations.js line 59 
`if(!promise.then) promise = Promise.resolve(promise)`

then use patch-package from npm to keep it as a patch.
not sure what the consequences are, but seems to be working with a fairly complex schema.

**Comment by jokklan** [comment]
I get the same error when writing `when`, validations, however only when using a function instead of `is: ...`.

**Comment by kevhiggins** [comment]
I was getting this error in yup 0.26.7 using a function instead of `is:`, and updating to 0.26.10 fixed the issue for me.
