### ISSUE TITLE
Using OneOf with OBJECT properties.

### ISSUE THREAD

**Issue by johnfarnell** [jquense/yup#463]
I have an object interface which looks like the following
```
{
sms : {
 body : String
}
email : {
 body : String
}
}
```
The object has a number of other properties in, but my requirement is to use yup to validate that either the sms property exists OR the email property exists. In other words, the object is invalid if neither property is supplied. I have successfully used mixed().test with an anonymous function for this, but I was wondering if mixed().oneOf would work. At the moment, I can make mixed.oneOf work if sms/email are strings, but I can't when they are objects.

**Comment by bsotodo** [comment]
Maybe something like
```javascript
Yup.mixed().oneOf([
  { sms   : { body : String },
  { email : { body : String },
])
```

**Comment by karlhorky** [comment]
The suggested code above does not work, @jquense maybe this can be reopened?

```ts
> const yup = require('yup')
> yup.mixed().oneOf([{ sms: {body: String}}, {email: {body: String}}])
> schema.validateSync({email:{body: 'abc'}})
Uncaught:
ValidationError: this must be one of the following values: [object Object], [object Object]
    at Object.createError (/Users/k/p/project/node_modules/yup/index.js:348:21)
    at Object.test (/Users/k/p/project/node_modules/yup/index.js:1125:55)
    at validate (/Users/k/p/project/node_modules/yup/index.js:389:35)
    at MixedSchema.runTests (/Users/k/p/project/node_modules/yup/index.js:825:7)
    at MixedSchema._validate (/Users/k/p/project/node_modules/yup/index.js:774:10)
    at MixedSchema.validateSync (/Users/k/p/project/node_modules/yup/index.js:889:12) {
  value: { email: { body: 'abc' } },
  path: '',
  type: 'oneOf',
  errors: [
    'this must be one of the following values: [object Object], [object Object]'
  ],
  params: {
    value: { email: [Object] },
    originalValue: { email: [Object] },
    label: undefined,
    path: '',
    spec: {
      strip: false,
      strict: false,
      abortEarly: true,
      recursive: true,
      nullable: false,
      optional: true,
      coarce: true
    },
    values: '[object Object], [object Object]',
    resolved: [ [Object], [Object] ]
  },
  inner: []
}
```

Wonder if this has anything to do with the internal data structure of `Set`, as noted here: #1393
