### ISSUE TITLE
Casting array subtypes fails

### ISSUE THREAD

**Issue by alathon** [jquense/yup#56]
```javascript
var yup = require('yup')
var expert = yup.array({
    date: yup.date()
  })

expert.cast([
    {date: '2014-09-23'}
])
```

Expected result:The date should be getting transformed into a Date object.

Actual result: On TonicDev, date remains a string; on my own Node instance, an error is thrown.

TonicDev example: https://tonicdev.com/alathon/yup-examples/2.0.2

When I do this on my own Node instance, I get the following error:

TypeError: _this2._subType.cast is not a function
    at /source/node_modules/yup/lib/array.js:70:30
    at Array.map (native)
    at ArraySchema._cast (/source/node_modules/yup/lib/array.js:69:18)
    at ArraySchema.cast (/source/node_modules/yup/lib/mixed.js:137:19)
    at /source/node_modules/yup/lib/object.js:113:60
    at Array.forEach (native)
    at transform (/source/node_modules/yup/lib/util/_.js:88:31)
    at ObjectSchema._cast (/source/node_modules/yup/lib/object.js:102:13)
    at ObjectSchema.cast (/source/node_modules/yup/lib/mixed.js:137:19)
    at _callee5$ (experts.js:177:25)
    at tryCatch (/source/node_modules/regenerator-runtime/runtime.js:62:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/source/node_modules/regenerator-runtime/runtime.js:336:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/source/node_modules/regenerator-runtime/runtime.js:95:21)
    at step (/source/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /source/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:20
    at run (/source/node_modules/core-js/modules/es6.promise.js:89:22)
    at /source/node_modules/core-js/modules/es6.promise.js:102:28
    at flush (/source/node_modules/core-js/modules/_microtask.js:18:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9

**Comment by alathon** [comment]
Interestingly, array().of(...) **does** work.

The following works, where the above does not:

```javascript
var yup = require('yup')
var expert = yup.array().of({
    date: yup.date()
  }))

expert.cast([
    {date: '2014-09-23'}
])
```

Is array({ shape }) not just a short-hand for array().of(object({ shape })) ?

**Comment by jquense** [comment]
using an object literal isn't short-hand for an object at all right now... I'm not sure why that would work in any case. you can use either of() directly or as the constructor argument but you need object,  it's `array(object({ date }))`

**Comment by alathon** [comment]
Yeah, that makes sense. I'll close the ticket then =)
